# Generated by Django 2.1.12 on 2020-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('a', 'Admin'), ('b', 'User')], default='user', max_length=30),
        ),
    ]
