# Generated by Django 2.1.12 on 2020-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200502_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='intchoices',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three')], default=0),
        ),
    ]
