# Generated by Django 2.1.12 on 2020-02-29 17:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('approved', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=30)),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('notes', models.TextField(blank=True)),
                ('description_explicit', models.TextField(blank=True)),
                ('description_implicit', ckeditor.fields.RichTextField(blank=True)),
                ('description_toolbar', models.TextField(blank=True)),
            ],
        ),
    ]
