# Generated by Django 1.9.7 on 2016-06-06 13:22
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django_ckeditor_example.models import Person


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[
                    ("Admin", "Admin"),
                    ("User", "User")
                ], max_length=30, default="User")),
                ('user_age', models.IntegerField(null=True)),
            ]
        )
    ]
